#!/bin/sh
#
# A hook script to find all recipe Markdown files and list them in the
# index.html page appropriately

RECIPES=$(find ./recipes/ | grep "\.md$" | sed 's/\.\/recipes\///g' \
          | sed 's/.*/"\0"/g' | awk '{print}' ORS=', ' | sed 's/, $//g')
REPLACE="let commitSetRecipes = [$RECIPES];"

sed -i.bak "s/let commitSetRecipes = \[.*\];/${REPLACE}/" ./index.html
rm ./index.html.bak
git add ./index.html
